######################################################################
# Automatically generated by qmake (2.01a) Sun 20. Jun 00:59:01 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Mainwindow.h menuwidget.h MiniMap.h
FORMS += Mainwindow.ui menuwidget.ui
SOURCES += main.cpp Mainwindow.cpp menuwidget.cpp MiniMap.cpp
